brew tap 'caskroom/cask'

# ZSH
# --------------------
brew 'zsh'
brew 'zsh-completions'


# DEV
# --------------------
brew 'git'
brew 'python3'


# Apps
# --------------------
# ↳ utils
#    cask 'alfred'
# ↳ browsers
    cask 'firefox'
    cask 'google-chrome'
# ↳ cloud
    cask 'dropbox'
    cask 'google-drive'
# ↳ dev 
    cask 'visual-studio-code'
    cask 'iterm2'
    cask 'sublime-text'


# Mac App Store
# --------------------
mas "1Password",    id: 443987910
mas "Xcode",        id: 497799835

