#!/bin/sh

SETTINGS_PATH=/mnt/c/Users/bohuim/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json
rm $SETTINGS_PATH
cp $HOME/dotfiles/WindowsTerminal/settings.json $SETTINGS_PATH
